#!/bin/bash

# @brief    Скрипт для сборки пакета в текущей среде

#
# Проверка места вызова скрипта
#

if ! [ -f "debian/changelog" ]
then
    echo "Unable to find debian/changelog!" >&2
    exit 1
fi

#
# Константы
#

# @brief    Версия скрипта
readonly COMMON_VERSION="1.0.0"

# @brief    Название скрипта
readonly COMMON_SCRIPT_FILE="$(basename "$0")"

# @brief    Путь к скрипту
readonly COMMON_SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

# @brief    Путь к лог файлу
readonly COMMON_LOG_FILE="/tmp/$COMMON_SCRIPT_FILE.log"

# @brief    Название пакета
readonly COMMON_PACKAGE_NAME="$(dpkg-parsechangelog -S Source)"

# @brief    Код успешного выполнения операции
readonly ALL_OK=0

# @brief    Код неуспешного выполнения операции
readonly NOT_OK=1

#
# Аргументы
#

# @brief    Флаг вывода логов
COMMON_IS_VERBOSE=0

# @brief    Путь к выходной директории
COMMON_OUTPUT_DIR="$COMMON_SCRIPT_DIR/../output"

#
# Функции
#

# @brief    Главная функция
# @details  Данная функция выполняет вызов prepare(), парсинг и проверку входных аргументов.
#               Затем выполняет вызов dpkg-buildpackage,
#               копирование выходных файлов в COMMON_OUTPUT_DIR и вызов debclean
# @return   Возвращает ALL_OK в случае успешного выполнения всех действий.
#               В противном случае, возвращает NOT_OK
function main ()
{
    if ! prepare
    then
        return $NOT_OK
    fi

    while [[ $# -gt 0 ]]
    do
        case $1 in
            -h|--help)
                printHelp
                exit $ALL_OK
            ;;
            -o|--output-path)
                COMMON_OUTPUT_DIR="$2"
                if ! mkdir -p "$COMMON_OUTPUT_DIR" >> "$COMMON_LOG_FILE" 2>&1
                then
                    echo "Unable to create output directory!"
                    return $NOT_OK
                fi
                shift
                shift
            ;;
            -v|--verbose)
                COMMON_IS_VERBOSE=1
                shift
            ;;
            -*)
                echo "Unknown option!"
                printHelp
                exit $NOT_OK
            ;;
            *)
                echo "Unknown argument!"
                printHelp
                exit $NOT_OK
            ;;
        esac
    done

    printMessage "Building the package... "
    if ! executeCommand dpkg-buildpackage -us -uc
    then
        printMessage "Error!\n"
        return $NOT_OK
    fi
    printMessage "Done!\n"
    
    printMessage "Prepairing the output files... "
    if ! executeCommand mv ../"$COMMON_PACKAGE_NAME"*.deb "$COMMON_OUTPUT_DIR"
    then
        printMessage "Error!\n"
        return $NOT_OK
    fi
    if ls ./*.ddeb 1> /dev/null 2>&1
    then
        if ! executeCommand mv ../"$COMMON_PACKAGE_NAME"*.ddeb "$COMMON_OUTPUT_DIR"
        then
            printMessage "Error!\n"
            return $NOT_OK
        fi
    fi
    printMessage "Done!\n"
    
    printMessage "Clean... "
    executeCommand debclean
    printMessage "Done!\n"

    return $ALL_OK
}

# @brief    Функция подготовки к работе
# @details  Данная функция выполняет создание лог-файла, проверку наличия зависимостей
#               и корректность окружения
# @return   Возвращает ALL_OK в случае успешной подготовки к работе.
#               В противном случае, возвращет NOT_OK
function prepare ()
{
    if ! truncate -s 0 "$COMMON_LOG_FILE"
    then
        echo "Failed to truncate $COMMON_LOG_FILE!"
        return $NOT_OK
    fi

    local DEPENDS=("script")
    local MESSAGE="Install the following binaries: \n"
    local IS_SATISFIED=$ALL_OK

    for BINARY in "${DEPENDS[@]}"
    do
        if ! command -v "$BINARY" >> /dev/null 2>&1
        then
            IS_SATISFIED=$NOT_OK
            MESSAGE+="$BINARY\n"
        fi
    done

    if [ $IS_SATISFIED == $NOT_OK ]
    then
        echo -e "$MESSAGE"
        return $NOT_OK
    fi

    return $ALL_OK
}

# @brief    Функция вывода help
# @return   Возвращает ALL_OK
function printHelp ()
{
    echo -e "Usage: scripts/$COMMON_SCRIPT_FILE [OPTIONS]"
    echo -e ""
    echo -e "Builds a package"
    echo -e ""
    echo -e "   -h --help         \t Shows this message"
    echo -e "   -v --verbose      \t Enables verbose output"
    echo -e "   -o --output-path  \t Sets output directory"
    echo -e ""
    echo -e "Log file is $COMMON_LOG_FILE"
    echo -e ""
    echo -e "Version $COMMON_VERSION"

    return $ALL_OK
}

# @brief    Функция выполнения команды
# @details  Данная функция выполняет все полученные аргументы,
#               перенаправляя их вывод в зависимости от значения COMMON_IS_VERBOSE
# @return   Возвращает результат выполнения всех полученных аргументов
function executeCommand()
{
    if [ $COMMON_IS_VERBOSE == 1 ]
    then
        script -q -a -e -c "$*" /dev/null | tee -a "$COMMON_LOG_FILE"
        return ${PIPESTATUS[0]}
    else
        script -q -a -e -c "$*" "$COMMON_LOG_FILE" > /dev/null
        return ${PIPESTATUS[0]}
    fi
}

# @brief    Функция вывода сообщения в stdout
# @details  Данная функция выполняет вывод MESSAGE в stdout, если COMMON_IS_VERBOSE сброшен
# @param    MESSAGE Выводимое сообщение
# @warning  Не выводит символ \n самостоятельно
# @note     MESSAGE может содержать Escape-последовательности
# @return   Всегда возвращает ALL_OK
function printMessage()
{
    if [ $COMMON_IS_VERBOSE == 1 ]
    then
        return $ALL_OK
    fi

    echo -en "$1"

    return $ALL_OK
}

#
# Точка входа в скрипт
#

main "$@"
exit $?
