#!/bin/bash

# @file     makeTests
# @brief    Скрипт проведения тестов для проверки утилиты ladder
# @param    COMMON_UTILITY Путь до тестируемой утилиты
# @param    DESIRED_TESTS Список желаемых тестов. Если пуст, будут выполнены все тесты из <COMMON_TESTS_DIR>

#
# Константы
#

# @brief    Директория скрипта
readonly COMMON_SCRIPT_DIR="$(dirname "$(realpath "$0")")"

# @brief    Название скрипта
readonly COMMON_SCRIPT_NAME="$(basename "$0")"

# @brief    Лог-файл
readonly COMMON_LOG="/tmp/$COMMON_SCRIPT_NAME.log"

# @brief    Директория с тестовым окружением
readonly COMMON_TESTS_DIR="$COMMON_SCRIPT_DIR/../tests"

# @brief    Путь до тестируемой утилиты
readonly COMMON_UTILITY="$1"; shift

# @brief    Название тестовых входных файлов
readonly COMMON_TEST_INPUT_FILE_NAME="testInputFile"

# @brief    Название тестовых выходных файлов
readonly COMMON_TEST_OUTPUT_FILE_NAME="testOutputFile"

# @brief    Суффикс выходных файлов утилиты
readonly COMMON_UTILITY_OUTPUT_FILE_SUFFIX="utility"

# @brief    Суффикс тестовых выходных файлов
readonly COMMON_TEST_OUTPUT_FILE_SUFFIX="diff"

#
# Цвета
#

# @brief    Красный цвет
readonly COMMON_RED='\033[31m'

# @brief    Желтый цвет
readonly COMMON_YELLOW='\033[33m'

# @brief    Зеленый цвет
readonly COMMON_GREEN='\033[32m'

# @brief    Сброс цвета
readonly COMMON_RESET='\033[0m'

#
# Общие переменные
#

# @brief    Флаг наличия meld в системе
COMMON_IS_MELD_EXISTS=0

# @brief    Список тестов
COMMON_TESTS_LIST=()

#
# Функции
#

# @brief    Основная функция скрипта
# @details  Данная функция выполняет вызов prepare() и
#               последовательное тестирование COMMON_UTILITY.
# @param    DESIRED_TESTS Список желаемых тестов. Если пуст, будут выполнены все тесты из <COMMON_TESTS_DIR>
# @return   Возвращает 0 в случае успешного создания тестовой среды.
#               В противном случае, возвращет 1
function main()
{
    local DESIRED_TESTS=("$@")

    if ! prepare
    then
        return 1
    fi

    local TESTS_RESULT_LIST=()
    for ((i = 0; i < ${#COMMON_TESTS_LIST[@]}; ++i))
    do
        local TEST="${COMMON_TESTS_LIST[$i]}"

        local IS_COMPARE_DESIRED=0

        if [[ "${#DESIRED_TESTS[@]}" -ne 0 ]]
        then                
            local DESIRED_TEST=""
            for DESIRED_TEST in "${DESIRED_TESTS[@]}"
            do
                if [ "$DESIRED_TEST" == "${TEST}_Compare" ]
                then
                    IS_COMPARE_DESIRED=1
                fi
            done
        else
            IS_COMPARE_DESIRED=1
        fi

        if [[ "$IS_COMPARE_DESIRED" == "1" ]]
        then
            TESTS_RESULT_LIST+=("${TEST} Compare")
            performCompareTest "${TEST}"
            TESTS_RESULT_LIST+=("$?")
        fi
    done

    if ((${#TESTS_RESULT_LIST[@]} == 0))
    then
        echo "There was not a single test"
        return 0
    fi

    local TEST_NAME_MAX_LENGTH=0
    local TEST_NUMBER_MAX_LENGTH=0
    for ((i = 0; i < ${#TESTS_RESULT_LIST[@]}; i+=2))
    do
        local TEST_NAME="$(echo "${TESTS_RESULT_LIST[$i]}" | cut -d ' ' -f1)"
        if [[ ${#TEST_NAME} -gt $TEST_NAME_MAX_LENGTH ]]
        then
            TEST_NAME_MAX_LENGTH=${#TEST_NAME}
        fi

        local TEST_NUMBER=$((i / 2))
        if [[ ${#TEST_NUMBER} -gt $TEST_NUMBER_MAX_LENGTH ]]
        then
            TEST_NUMBER_MAX_LENGTH=${#TEST_NUMBER}
        fi
    done

    local TEST_TYPE_MAX_LENGTH=0
    local TYPE=""
    local TEST_TYPES_LIST=("Compare")
    for TYPE in "${TEST_TYPES_LIST[@]}"
    do
        if [[ ${#TYPE} -gt $TEST_TYPE_MAX_LENGTH ]]
        then
            TEST_TYPE_MAX_LENGTH=${#TYPE}
        fi
    done

    local PASSED_COUNT=0
    local FAILED_COUNT=0
    echo -e "\nSummary:"
    for ((i = 0; i < ${#TESTS_RESULT_LIST[@]}; i+=2))
    do
        local TEST="$(echo "${TESTS_RESULT_LIST[$i]}" | cut -d ' ' -f1)"
        local TYPE="$(echo "${TESTS_RESULT_LIST[$i]}" | cut -d ' ' -f2)"
        local RESULT="${TESTS_RESULT_LIST[$i + 1]}"
        local TEST_NUMBER=$((i / 2))

        if [[ $RESULT -eq 0 ]]
        then
            echo -en "$COMMON_GREEN"
            RESULT="Passed"
            ((PASSED_COUNT++))
        else
            echo -en "$COMMON_RED"
            RESULT="Failed"
            ((FAILED_COUNT++))

            local TEST_FILE_ORIGINAL="$COMMON_TESTS_DIR/${TEST}/${COMMON_TEST_OUTPUT_FILE_NAME}"
            local TEST_FILE_TEXT="$COMMON_TESTS_DIR/${TEST}_${TYPE}.${COMMON_TEST_OUTPUT_FILE_SUFFIX}.txt"

            local UTILITY_FILE_ORIGINAL="$COMMON_TESTS_DIR/${TEST}_${TYPE}.${COMMON_UTILITY_OUTPUT_FILE_SUFFIX}"
            local UTILITY_FILE_TEXT="${UTILITY_FILE_ORIGINAL}.txt"

            if [ -f "$TEST_FILE_ORIGINAL" ] && [ -f "$UTILITY_FILE_ORIGINAL" ]
            then
                od -tx1 -v "$TEST_FILE_ORIGINAL"    > "$TEST_FILE_TEXT"
                od -tx1 -v "$UTILITY_FILE_ORIGINAL" > "$UTILITY_FILE_TEXT"
            fi

            if [ "$COMMON_IS_MELD_EXISTS" == "1" ] && [ "${TYPE}" == "Compare" ] && [ -f "$TEST_FILE_TEXT" ] && [ -f "$UTILITY_FILE_TEXT" ]
            then
                meld -n "$TEST_FILE_TEXT" "$UTILITY_FILE_TEXT" &
            fi
        fi

        printf "[%*d] %-*s %-*s %s" "$TEST_NUMBER_MAX_LENGTH" "$((TEST_NUMBER + 1))" "$TEST_NAME_MAX_LENGTH" "$TEST" "$TEST_TYPE_MAX_LENGTH" "$TYPE" "$RESULT"

        echo -e "$COMMON_RESET"
    done

    echo

    if [[ "$FAILED_COUNT" -gt 0 ]]
    then
        echo -en "$COMMON_RED"
        echo -n  "Failed $FAILED_COUNT/$((${#TESTS_RESULT_LIST[@]}/2))"
        echo -e  "$COMMON_RESET"
    fi

    if [[ "$PASSED_COUNT" -gt 0 ]]
    then
        echo -en "$COMMON_GREEN"
        echo -n  "Passed $PASSED_COUNT/$((${#TESTS_RESULT_LIST[@]}/2))"
        echo -e  "$COMMON_RESET"
    fi

    echo

    printDetails

    return 0
}

# @brief    Функция подготовки рабочего окружения
# @details  Данная функция выполняет проверку существования тестируемой утилиты,
#               проверку существования тестовой среды, её очистку от логов тестов,
#               проверку наличия meld, создание лог-файла и
#               формирует список тестов в переменной <COMMON_TESTS_LIST>
# @return   Возвращает 0 в случае успешной подготовки рабочего окружения.
#               В противном случае, возвращет 1
function prepare()
{
    if ! truncate -s 0 "$COMMON_LOG"
    then
        echo "Failed to truncate $COMMON_LOG!"
        return 1
    fi

    if ! [ -x "$COMMON_UTILITY" ]
    then
        echo -e "Utility doesn't exist! Use:\n\tmake\nThen pass path to utility as first argument"
        return 1
    fi

    if ! [ -d "$COMMON_TESTS_DIR" ]
    then
        echo -e "Test environment doesn't exist! Use:\n\tscripts/makeTestEnv"
        return 1
    fi

    local TESTS_LIST=()
    local TESTS_LIST_SORTED=()

    TESTS_LIST=("$COMMON_TESTS_DIR"/*)
    mapfile -t TESTS_LIST_SORTED < <(
        printf '%s\n' "${TESTS_LIST[@]}" \
        | awk '{ print length, $0 }'     \
        | sort -rn                       \
        | cut -d' ' -f2-
    )

    COMMON_TESTS_LIST=()

    local TEST=""
    for TEST in "${TESTS_LIST_SORTED[@]}"
    do
        if [ -d "$TEST" ]
        then
            COMMON_TESTS_LIST+=("$(basename "$TEST")")
        fi
        if [ -f "$TEST" ]
        then
            rm "$COMMON_TESTS_DIR/$(basename "$TEST")"
        fi
    done

    if command -v meld >> /dev/null 2>&1
    then
        COMMON_IS_MELD_EXISTS=1
    fi

    return 0
}

# @brief    Функция вывода сообщения с командой для получения деталей об ошибке
function printDetails()
{
    echo -e "Details:\n\tcat $COMMON_LOG"
}

# @brief    Функция выполнения теста, сравнивающего выходной файл утилиты с тестовый выходной файл
# @details  Данная функция выполняет: <br>
#               - Запуск COMMON_UTILITY с указанием входного файла как UTILITY_OUTPUT_FILE, а выходного как UTILITY_INPUT_FILE<br>
#               - Запуск diff TEST_OUTPUT_FILE UTILITY_OUTPUT_FILE для проверки теста на успешность 
# @param    TEST Название теста
# @return   Возвращает 0, если выходной файл утилиты и тестовый выходной файл идентичны
#               В противном случае, возвращает 1
function performCompareTest()
{
    local TEST="ANON"

    if [ -n "$1" ]
    then
        TEST="$1"
    fi

    local TEST_FULL_NAME="${TEST}_Compare"

    local UTILITY_OUTPUT_FILE="$COMMON_TESTS_DIR/${TEST_FULL_NAME}.${COMMON_UTILITY_OUTPUT_FILE_SUFFIX}"
    local TEST_INPUT_FILE="$COMMON_TESTS_DIR/${TEST}/$COMMON_TEST_INPUT_FILE_NAME"
    local TEST_OUTPUT_FILE="$COMMON_TESTS_DIR/${TEST}/$COMMON_TEST_OUTPUT_FILE_NAME"

    echo

    echo -en "${COMMON_YELLOW}"
    echo     "=====${TEST}====="                                                                       | tee -a "$COMMON_LOG"
    echo     "UTILITY_OUTPUT_FILE is $(realpath --relative-to=. "$UTILITY_OUTPUT_FILE"  2> /dev/null)" | tee -a "$COMMON_LOG"
    echo     "TEST_INPUT_FILE     is $(realpath --relative-to=. "$TEST_INPUT_FILE"      2> /dev/null)" | tee -a "$COMMON_LOG"
    echo -n  "TEST_OUTPUT_FILE    is $(realpath --relative-to=. "$TEST_OUTPUT_FILE"     2> /dev/null)" | tee -a "$COMMON_LOG" && echo "" >> "$COMMON_LOG"
    echo -e  "${COMMON_RESET}"

    if ! truncate -s 0 "$UTILITY_OUTPUT_FILE" >> /dev/null 2>&1
    then
        echo -en "${COMMON_RED}"
        echo -n  "Failed to create $UTILITY_OUTPUT_FILE file" | tee -a "$COMMON_LOG" && echo "" >> "$COMMON_LOG"
        echo -e  "${COMMON_RESET}"
        return 1
    fi

    "$COMMON_UTILITY" -o "$TEST_OUTPUT_FILE" "$TEST_INPUT_FILE" >> "$COMMON_LOG" 2>&1

    if ! diff "$TEST_OUTPUT_FILE" "$UTILITY_OUTPUT_FILE" >> /dev/null 2>&1
    then
        echo -en "${COMMON_RED}"
        echo -n  "Test failed: TEST_OUTPUT_FILE and UTILITY_OUTPUT_FILE differs" | tee -a "$COMMON_LOG" && echo "" >> "$COMMON_LOG"
        echo -e  "${COMMON_RESET}"
        return 1
    fi

    echo -en "${COMMON_GREEN}"
    echo -n  "Test passed" | tee -a "$COMMON_LOG" && echo "" >> "$COMMON_LOG"
    echo -e  "${COMMON_RESET}"

    return 0
}

#
# Точка входа в скрипт
#

main "$@"
exit $?
