#!/bin/bash

# @file     testDataGenerator
# @brief    Скрипт создания файлов данных для проверки утилиты ladder
# @details  Данный скрипт выполняет создание входного и соответствующего ему выходного файла для проверки утилиты ladder

#
# Константы
#

# @brief    Директория скрипта
readonly COMMON_SCRIPT_DIR="$(dirname "$(realpath "$0")")"

# @brief    Название скрипта
readonly COMMON_SCRIPT_NAME="$(basename "$0")"

# @brief    Минимальное количество бит мусорных бит в начале временного файла
readonly COMMON_TEMP_FILE_GARBAGE_BEFORE_MIN="0"

# @brief    Минимальное количество бит мусорных бит в конце временного файла
readonly COMMON_TEMP_FILE_GARBAGE_AFTER_MIN="0"

# @brief    Минимальное количество генерируемых пакетов во временном файле
readonly COMMON_TEMP_FILE_PACKETS_COUNT_MIN="1"

# @brief    Минимальное количество бит в каждом генерируемом пакете во временном файле
readonly COMMON_TEMP_FILE_PACKET_LENGTH_MIN="${#TEMP_FILE_SYNC_MARK}"

# @brief    Минимальное количество байт до первого синхроимпульса во входном файле
readonly COMMON_INPUT_FILE_GARBAGE_BEFORE_MIN="0"

# @brief    Минимальное количество байт после последнего синхроимпульса во входном файле
readonly COMMON_INPUT_FILE_GARBAGE_AFTER_MIN="0"

# @brief    Минимальная длина каждого синхроимпульса во входном файле
readonly COMMON_INPUT_FILE_SYNC_LENGTH_MIN="1"

# @brief    Минимальная длина каждого информационного уровня во входном файле
readonly COMMON_INPUT_FILE_DATA_LENGTH_MIN="1"

# @brief    Код успешного выполнения операции
readonly ALL_OK=0

# @brief    Код неуспешного выполнения операции
readonly NOT_OK=1

#
# Константы для генерации временного файла
#

# @brief    Суффикс временного файла для генерации входного файла
readonly TEMP_FILE_SUFFIX_FOR_INPUT="for_input"

# @brief    Суффикс временного файла для генерации выходного файла
readonly TEMP_FILE_SUFFIX_FOR_OUTPUT="for_output"

# @brief    Синхромаркер
readonly TEMP_FILE_SYNC_MARK="00011010110011111111110000011101"

#
# Константы для генерации входного файла
#

# @brief    Логический уровень, соответствующий биту 0
readonly INPUT_FILE_LEVEL_DATA_0=0

# @brief    Логический уровень, соответствующий биту 1
readonly INPUT_FILE_LEVEL_DATA_1=1

# @brief    Логический уровень, соответствующий синхроимпульсу
readonly INPUT_FILE_LEVEL_SYNC=2

# @brief    Байт входного файла, соответствующий биту 0
readonly INPUT_FILE_ENCODED_DATA_0=$'\xFD'

# @brief    Байт входного файла, соответствующий биту 1
readonly INPUT_FILE_ENCODED_DATA_1=$'\xFE'

# @brief    Байт входного файла, соответствующий синхроимпульсу
readonly INPUT_FILE_ENCODED_SYNC=$'\xFF'

#
# Аргументы
#

# @brief    Путь до временного файла
COMMON_TEMP_FILE_PATH="$COMMON_SCRIPT_DIR/$COMMON_SCRIPT_NAME.temp"

# @brief    Количество бит мусорных бит в начале временного файла
# @warning  Любое беззнаковое целочисленное число, больше COMMON_TEMP_FILE_GARBAGE_BEFORE_MIN
COMMON_TEMP_FILE_GARBAGE_BEFORE="$COMMON_TEMP_FILE_GARBAGE_BEFORE_MIN"

# @brief    Количество бит мусорных бит в конце временного файла
# @warning  Любое беззнаковое целочисленное число, больше COMMON_TEMP_FILE_GARBAGE_AFTER_MIN
COMMON_TEMP_FILE_GARBAGE_AFTER="$COMMON_TEMP_FILE_GARBAGE_AFTER_MIN"

# @brief    Количество генерируемых пакетов во временном файле
# @warning  Любое беззнаковое целочисленное число, больше COMMON_TEMP_FILE_PACKETS_COUNT_MIN
COMMON_TEMP_FILE_PACKETS_COUNT="$COMMON_TEMP_FILE_PACKETS_COUNT_MIN"

# @brief    Шанс повреждения синхромаркера в каждом генерируемом пакете во временном файле
# @warning  Любое беззнаковое целочисленное число в диапазоне [0:100]
COMMON_TEMP_FILE_SYNC_MARK_CORRUPT_CHANCE="0"

# @brief    Шанс повреждения данных в каждом генерируемом пакете во временном файле
# @warning  Любое беззнаковое целочисленное число в диапазоне [0:100]
COMMON_TEMP_FILE_DATA_CORRUPT_CHANCE="0"

# @brief    Количество бит в каждом генерируемом пакете во временном файле
# @warning  Любое беззнаковое целочисленное число, больше COMMON_TEMP_FILE_PACKET_LENGTH_MIN
COMMON_TEMP_FILE_PACKET_LENGTH="$COMMON_TEMP_FILE_PACKET_LENGTH_MIN"

# @brief    Путь к создаваемому входному файлу
COMMON_INPUT_FILE_PATH="$COMMON_SCRIPT_DIR/$COMMON_SCRIPT_NAME.input"

# @brief    Количество байт до первого синхроимпульса во входном файле
# @warning  Любое беззнаковое целочисленное число, больше COMMON_INPUT_FILE_GARBAGE_BEFORE_MIN
COMMON_INPUT_FILE_GARBAGE_BEFORE="$COMMON_INPUT_FILE_GARBAGE_BEFORE_MIN"

# @brief    Количество байт после последнего синхроимпульса во входном файле
# @warning  Любое беззнаковое целочисленное число, больше COMMON_INPUT_FILE_GARBAGE_AFTER_MIN
COMMON_INPUT_FILE_GARBAGE_AFTER="$COMMON_INPUT_FILE_GARBAGE_AFTER_MIN"

# @brief    Длина каждого синхроимпульса во входном файле
# @warning  Любое беззнаковое целочисленное число, больше COMMON_INPUT_FILE_SYNC_LENGTH_MIN
COMMON_INPUT_FILE_SYNC_LENGTH="$COMMON_INPUT_FILE_SYNC_LENGTH_MIN"

# @brief    Длина каждого информационного уровня во входном файле
# @warning  Любое беззнаковое целочисленное число, больше COMMON_INPUT_FILE_DATA_LENGTH_MIN
COMMON_INPUT_FILE_DATA_LENGTH="$COMMON_INPUT_FILE_DATA_LENGTH_MIN"

# @brief    Шанс повреждения каждого информационного уровня во входном файле
# @warning  Любое беззнаковое целочисленное число в диапазоне [0:100]
COMMON_INPUT_FILE_LEVEL_CORRUPT_CHANCE="0"

# @brief    Путь к выходному файлу
COMMON_OUTPUT_FILE_PATH="$COMMON_SCRIPT_DIR/$COMMON_SCRIPT_NAME.output"

#
# Функции
#

# @brief    Функция завершения работы скрипта
# @details  Данная функция выполняет удаление созданных функцией tempFileGenerate() временных файлов
function cleanup()
{
    rm "${COMMON_TEMP_FILE_PATH}.${TEMP_FILE_SUFFIX_FOR_INPUT}"  2> /dev/null
    rm "${COMMON_TEMP_FILE_PATH}.${TEMP_FILE_SUFFIX_FOR_OUTPUT}" 2> /dev/null
}

# @brief    Главная функция
# @details  Данная функция выполняет парсинг и проверку входных аргументов.
#           Затем выполняет генерацию временных файлов, затем конвертирует их во входной и выходной файл,
#               после чего удаляет временные файлы
# @return   Возвращает ALL_OK в случае успешного выполнения всех действий.
#               В противном случае, возвращает NOT_OK
function main()
{
    while [[ $# -gt 0 ]]
    do
        case $1 in
            -tp|--temp-file-path)
                if [ -n "$2" ]
                then
                    COMMON_TEMP_FILE_PATH="$2"
                fi
                shift
                shift
            ;;
            -tb|--temp-file-garbage-before)
                COMMON_TEMP_FILE_GARBAGE_BEFORE=$(validateUInt "$2" "$COMMON_TEMP_FILE_GARBAGE_BEFORE_MIN")
                shift
                shift
            ;;
            -ta|--temp-file-garbage-after)
                COMMON_TEMP_FILE_GARBAGE_AFTER=$(validateUInt "$2" "$COMMON_TEMP_FILE_GARBAGE_AFTER_MIN")
                shift
                shift
            ;;
            -tc|--temp-file-packets-count)
                COMMON_TEMP_FILE_PACKETS_COUNT=$(validateUInt "$2" "$COMMON_TEMP_FILE_PACKETS_COUNT_MIN")
                shift
                shift
            ;;
            -ts|--temp-file-sync-mark-corrupt-chance)
                COMMON_TEMP_FILE_SYNC_MARK_CORRUPT_CHANCE=$(validateChance "$2")
                shift
                shift
            ;;
            -td|--temp-file-data-corrupt-chance)
                COMMON_TEMP_FILE_DATA_CORRUPT_CHANCE=$(validateChance "$2")
                shift
                shift
            ;;
            -tl|--temp-file-packet-length)
                COMMON_TEMP_FILE_PACKET_LENGTH=$(validateUInt "$2" "$COMMON_TEMP_FILE_PACKET_LENGTH_MIN")
                shift
                shift
            ;;
            -ip|--input-file-path)
                if [ -n "$2" ]
                then
                    COMMON_INPUT_FILE_PATH="$2"
                fi
                shift
                shift
            ;;
            -ib|--input-file-garbage-before)
                COMMON_INPUT_FILE_GARBAGE_BEFORE=$(validateUInt "$2" "$COMMON_INPUT_FILE_GARBAGE_BEFORE_MIN")
                shift
                shift
            ;;
            -ia|--input-file-garbage-after)
                COMMON_INPUT_FILE_GARBAGE_AFTER=$(validateUInt "$2" "$COMMON_INPUT_FILE_GARBAGE_AFTER_MIN")
                shift
                shift
            ;;
            -is|--input-file-sync-length)
                COMMON_INPUT_FILE_SYNC_LENGTH=$(validateUInt "$2" "$COMMON_INPUT_FILE_SYNC_LENGTH_MIN")
                shift
                shift
            ;;
            -id|--input-file-data-length)
                COMMON_INPUT_FILE_DATA_LENGTH=$(validateUInt "$2" "$COMMON_INPUT_FILE_DATA_LENGTH_MIN")
                shift
                shift
            ;;
            -il|--input-file-level-corrupt-chance)
                COMMON_INPUT_FILE_LEVEL_CORRUPT_CHANCE=$(validateChance "$2")
                shift
                shift
            ;;
            -op|--output-file-path)
                if [ -n "$2" ]
                then
                    COMMON_OUTPUT_FILE_PATH="$2"
                fi
                shift
                shift
            ;;
            -h|--help)
                printHelp
                exit $ALL_OK
            ;;
            -*)
                echo "Unknown option!"
                printHelp
                exit $NOT_OK
            ;;
            *)
                echo "Unknown argument!"
                printHelp
                exit $NOT_OK
            ;;
        esac
    done

    if ! tempFileGenerate
    then
        echo "Failed to generate temp files!" >&2
        return $NOT_OK
    fi

    if ! inputFileEncodeTempFile
    then
        echo "Failed to generate input file!" >&2
        return $NOT_OK
    fi

    if ! outputFileEncodeTempFile
    then
        echo "Failed to generate output file!" >&2
        return $NOT_OK
    fi

    return $ALL_OK
}

# @brief    Функция вывода help
# @return   Возвращает ALL_OK
function printHelp ()
{
    echo -e "Usage: $(realpath --relative-to=. "$COMMON_SCRIPT_DIR" 2> /dev/null)/$COMMON_SCRIPT_NAME [OPTIONS]"
    echo -e ""
    echo -e "Creates an input and output file with the specified options"
    echo -e ""
    echo -e "  -tp --temp-file-path                     \t Sets the path to the temporary file"
    echo -e "  -tb --temp-file-garbage-before           \t Sets the number of bits of garbage data at the beginning of the temporary file"
    echo -e "  -ta --temp-file-garbage-after            \t Sets the number of bits of garbage data at the end of the temporary file"
    echo -e "  -tc --temp-file-packets-count            \t Sets the number of generated packets in a temporary file"
    echo -e "  -ts --temp-file-sync-mark-corrupt-chance \t Sets the chance to corrupt the synchromarker in each generated packet in a temporary file"
    echo -e "  -td --temp-file-data-corrupt-chance      \t Sets the chance to corrupt the data in each generated packet in a temporary file"
    echo -e "  -tl --temp-file-packet-length            \t Sets the number of bits in each generated packet in the temporary file"
    echo -e "  -ip --input-file-path                    \t Sets the path to the input file"
    echo -e "  -ib --input-file-garbage-before          \t Sets the number of bytes before the first synchropulse in the input file"
    echo -e "  -ia --input-file-garbage-after           \t Sets the number of bytes after the last synchropulse in the input file"
    echo -e "  -is --input-file-sync-length             \t Sets the length of each synchropulse in the input file"
    echo -e "  -id --input-file-data-length             \t Sets the length of each information level in the input file"
    echo -e "  -il --input-file-level-corrupt-chance    \t Sets the chance to corrupt each information level in the input file"
    echo -e "  -op --output-file-path                   \t Sets the path to the output file"
    echo -e "  -h  --help                               \t Shows this message"
    echo -e ""

    return $ALL_OK
}

# @brief    Функция валидации целочисленного неотрицательного значения
# @details  Данная функция выполняет проверку VALUE. Если оно некорректно,
#               записывает в него значение DEFAULT
# @param    VALUE    Проверяемое значение
# @param    DEFAULT  Значение по умолчанию
# @note     Если DEFAULT не является целочисленным неотрицательным значением, он будет заменен на 0
# @return   Возвращает валидированное значение
function validateUInt()
{
    local VALUE=$1
    local DEFAULT=$2

    [[ "$DEFAULT" =~ ^[0-9]+$ ]] || DEFAULT=0

    [[ "$VALUE" =~ ^[0-9]+$ ]] || VALUE=$DEFAULT

    printf "%d" "$VALUE"
}

# @brief    Функция валидации шанса
# @details  Данная функция выполняет проверку VALUE. Если оно некорректно,
#               записывает в него 0
# @param    VALUE Проверяемое значение
# @return   Возвращает валидированное значение
function validateChance()
{
    local VALUE

    VALUE=$(validateUInt "$1" 0)

    ((VALUE > 100)) && VALUE=0

    printf "%d" "$VALUE"
}

# @brief    Функция получения шанса
# @details  Данная функция создает случайное число в диапазоне [0:100]
# @return   Возвращает сгенерированное значение шанса
function randomChance()
{
    echo $((RANDOM % 101))
}

#
# Функции для генерации временных файлов
#

# @brief    Функция генерации временных файлов
# @details  Данная функция выполняет очистку и заполнение сгенерированными данными 2-х временных файлов, представляющих собой
#               последовательность бит, в которой находятся данные, начинающиеся с синхромаркера.
#           В файл с суффиксом TEMP_FILE_SUFFIX_FOR_INPUT пишутся все сгенерированные функцией данные.
#           В файл с суффиксом TEMP_FILE_SUFFIX_FOR_OUTPUT пишутся только те сгенерированные функцией данные, которые должны попасть в выходной файл
# @warning  После использования временных файлов, их рекомендуется удалить
# @note     Используемые переменные:
#           COMMON_TEMP_FILE_PATH
#           COMMON_TEMP_FILE_GARBAGE_BEFORE
#           COMMON_TEMP_FILE_GARBAGE_AFTER
#           COMMON_TEMP_FILE_PACKETS_COUNT
#           COMMON_TEMP_FILE_SYNC_MARK_CORRUPT_CHANCE
#           COMMON_TEMP_FILE_DATA_CORRUPT_CHANCE
#           COMMON_TEMP_FILE_PACKET_LENGTH
# @param    TEMP_FILE_PATH Путь до временного файла
# @return   Возвращает ALL_OK в случае успешного создания временных файлов.
#               В противном случае, возвращает NOT_OK
function tempFileGenerate()
{
    local TEMP_FILE_FOR_INPUT_PATH="${COMMON_TEMP_FILE_PATH}.${TEMP_FILE_SUFFIX_FOR_INPUT}"
    local TEMP_FILE_FOR_OUTPUT_PATH="${COMMON_TEMP_FILE_PATH}.${TEMP_FILE_SUFFIX_FOR_OUTPUT}"

    truncate -s 0 "$TEMP_FILE_FOR_INPUT_PATH"  || return $NOT_OK
    truncate -s 0 "$TEMP_FILE_FOR_OUTPUT_PATH" || return $NOT_OK

    exec 3>>"$TEMP_FILE_FOR_INPUT_PATH"
    exec 4>>"$TEMP_FILE_FOR_OUTPUT_PATH"

    if ((COMMON_TEMP_FILE_GARBAGE_BEFORE > 0))
    then
        tempFileGenerateBits "$COMMON_TEMP_FILE_GARBAGE_BEFORE"
        printf "%s\n" "$COMMON_TEMP_FILE_GENERATED_BITS" >&3
    fi

    local i=0
    local IS_FIRST_PACKET_WITH_NOT_CORRUPTED_SYNC_MARK_WRITTEN=0
    for ((i = 0; i < COMMON_TEMP_FILE_PACKETS_COUNT; ++i))
    do
        tempFileGeneratePacket "$COMMON_TEMP_FILE_SYNC_MARK_CORRUPT_CHANCE" "$COMMON_TEMP_FILE_DATA_CORRUPT_CHANCE" "$COMMON_TEMP_FILE_PACKET_LENGTH"

        printf "%s\n" "$COMMON_TEMP_FILE_GENERATED_PACKET_BITS" >&3

        if ((COMMON_TEMP_FILE_GENERATED_PACKET_IS_SYNC_MARK_CORRUPTED == 0))
        then
            if ((IS_FIRST_PACKET_WITH_NOT_CORRUPTED_SYNC_MARK_WRITTEN == 1))
            then
                printf "\n" >&4
            fi
            IS_FIRST_PACKET_WITH_NOT_CORRUPTED_SYNC_MARK_WRITTEN=1
        fi

        if ((IS_FIRST_PACKET_WITH_NOT_CORRUPTED_SYNC_MARK_WRITTEN == 1))
        then
            printf "%s" "$COMMON_TEMP_FILE_GENERATED_PACKET_BITS" >&4
        fi
    done

    if ((COMMON_TEMP_FILE_GARBAGE_AFTER > 0))
    then
        tempFileGenerateBits "$COMMON_TEMP_FILE_GARBAGE_AFTER"
        printf "%s\n" "$COMMON_TEMP_FILE_GENERATED_BITS" >&3
    fi

    exec 3>&-
    exec 4>&-

    return $ALL_OK
}

# @brief    Сгенерированная функцией tempFileGeneratePacket() последовательность бит, представляющая собой пакет
COMMON_TEMP_FILE_GENERATED_PACKET_BITS=""

# @brief    Флаг поврежденности синхромаркера в сгенерированном функцией tempFileGeneratePacket() пакете
COMMON_TEMP_FILE_GENERATED_PACKET_IS_SYNC_MARK_CORRUPTED=0

# @brief    Флаг поврежденности данных в сгенерированном функцией tempFileGeneratePacket() пакете
COMMON_TEMP_FILE_GENERATED_PACKET_IS_DATA_CORRUPTED=0

# @brief    Функция генерации пакета для временного файла
# @details  Данная функция выполняет генерацию последовательности бит длиной PACKET_LENGTH, 
#               записывая её в COMMON_TEMP_FILE_GENERATED_PACKET_BITS.
#           Она состоит из синхромаркера, сгенерированного при помощи tempFileGenerateSyncMark() и
#               данных, сгенерированных при помощи tempFileGenerateBits().
#           Если случайное значение [0:100] меньше DATA_CORRUPT_CHANCE, 
#               длина итоговой последовательности будет изменена в пределах 5% от PACKET_LENGTH.
#           Флаг повреждения синхромаркера пакета записывается в COMMON_TEMP_FILE_GENERATED_PACKET_IS_SYNC_MARK_CORRUPTED.
#           Флаг повреждения данных        пакета записывается в COMMON_TEMP_FILE_GENERATED_PACKET_IS_DATA_CORRUPTED
# @param    SYNC_MARK_CORRUPT_CHANCE Шанс повреждения синхромаркера. Должен быть в диапазоне [0:100]
# @param    DATA_CORRUPT_CHANCE      Шанс повреждения данных пакета. Должен быть в диапазоне [0:100]
# @param    PACKET_LENGTH            Количество бит в генерируемом пакете. Должно быть не меньше ${#TEMP_FILE_SYNC_MARK}
# @return   Всегда возвращает ALL_OK
function tempFileGeneratePacket()
{
    local SYNC_MARK_CORRUPT_CHANCE="$1"
    local DATA_CORRUPT_CHANCE="$2"
    local PACKET_LENGTH="$3"

    COMMON_TEMP_FILE_GENERATED_PACKET_BITS=""
    COMMON_TEMP_FILE_GENERATED_PACKET_IS_SYNC_MARK_CORRUPTED=0
    COMMON_TEMP_FILE_GENERATED_PACKET_IS_DATA_CORRUPTED=0

    tempFileGenerateSyncMark "$SYNC_MARK_CORRUPT_CHANCE"
    local IS_SYNC_MARK_CORRUPTED=$COMMON_TEMP_FILE_GENERATED_SYNC_MARK_IS_CORRUPTED

    ((PACKET_LENGTH-="${#TEMP_FILE_SYNC_MARK}"))

    local PACKET_LENGTH_OFFSET=0
    local IS_DATA_CORRUPTED=0
    if (($(randomChance) < DATA_CORRUPT_CHANCE))
    then
        IS_DATA_CORRUPTED=1
        PACKET_LENGTH_OFFSET=$((PACKET_LENGTH * 5 / 100))

        if (($(randomChance) < 50))
        then
            ((PACKET_LENGTH+=PACKET_LENGTH_OFFSET))
        else
            ((PACKET_LENGTH-=PACKET_LENGTH_OFFSET))
        fi
    fi

    while true
    do
        tempFileGenerateBits "$PACKET_LENGTH"

        if ((IS_SYNC_MARK_CORRUPTED == 0))
        then
            [[ "$COMMON_TEMP_FILE_GENERATED_BITS" == *"$COMMON_TEMP_FILE_GENERATED_SYNC_MARK_BITS"* ]] && continue
        fi

        break
    done

    COMMON_TEMP_FILE_GENERATED_PACKET_BITS="${COMMON_TEMP_FILE_GENERATED_SYNC_MARK_BITS}${COMMON_TEMP_FILE_GENERATED_BITS}"
    COMMON_TEMP_FILE_GENERATED_PACKET_IS_SYNC_MARK_CORRUPTED=$IS_SYNC_MARK_CORRUPTED
    COMMON_TEMP_FILE_GENERATED_PACKET_IS_DATA_CORRUPTED=$IS_DATA_CORRUPTED

    return $ALL_OK
}

# @brief    Сгенерированная функцией tempFileGenerateSyncMark() последовательность бит, представляющая собой синхромаркер
COMMON_TEMP_FILE_GENERATED_SYNC_MARK_BITS=""

# @brief    Флаг поврежденности синхромаркера в сгенерированной функцией tempFileGenerateSyncMark() последовательности бит
COMMON_TEMP_FILE_GENERATED_SYNC_MARK_IS_CORRUPTED=0

# @brief    Функция генерации синхромаркера для временного файла
# @details  Данная функция выполняет запись TEMP_FILE_SYNC_MARK в COMMON_TEMP_FILE_GENERATED_SYNC_MARK_BITS.
#           Если случайное значение [0:100] меньше CORRUPT_CHANCE, случайный бит COMMON_TEMP_FILE_GENERATED_SYNC_MARK_BITS
#               будет инвертирован.
#           Флаг повреждения синхромаркера записывается в COMMON_TEMP_FILE_GENERATED_SYNC_MARK_IS_CORRUPTED
# @param    CORRUPT_CHANCE Шанс, что сгенерированная последовательность бит будет повреждена. Должен быть в диапазоне [0:100]
# @return   Всегда возвращает $ALL_OK 
function tempFileGenerateSyncMark()
{
    local CORRUPT_CHANCE="$1"

    local RESULT="$TEMP_FILE_SYNC_MARK"
    local IS_SYNC_MARK_CORRUPTED=0

    COMMON_TEMP_FILE_GENERATED_SYNC_MARK_BITS=""
    COMMON_TEMP_FILE_GENERATED_SYNC_MARK_IS_CORRUPTED=0

    if (($(randomChance) < CORRUPT_CHANCE))
    then
        IS_SYNC_MARK_CORRUPTED=1

        local POSITION=$((RANDOM % ${#TEMP_FILE_SYNC_MARK}))

        RESULT="${RESULT:0:POSITION}$((1 - ${RESULT:POSITION:1}))${RESULT:POSITION+1}"
    fi

    COMMON_TEMP_FILE_GENERATED_SYNC_MARK_BITS="$RESULT"
    COMMON_TEMP_FILE_GENERATED_SYNC_MARK_IS_CORRUPTED=$IS_SYNC_MARK_CORRUPTED

    return $ALL_OK
}

# @brief    Сгенерированная функцией tempFileGenerateBits() последовательность бит
COMMON_TEMP_FILE_GENERATED_BITS=""

# @brief    Функция генерации последовательности бит указанной длины для временного файла
# @details  Данная функция выполняет генерацию последовательности бит длиной LENGTH, 
#               записывая её в COMMON_TEMP_FILE_GENERATED_BITS
# @param    LENGTH Длина генерируемой последовательности бит. Должна быть не меньше 0
# @return   Всегда возвращает $ALL_OK
function tempFileGenerateBits()
{
    local LENGTH="$1"

    local RESULT=""

    COMMON_TEMP_FILE_GENERATED_BITS=""

    while ((${#RESULT} < LENGTH))
    do
        RESULT+="$((RANDOM % 2))"
        ((${#RESULT} >= LENGTH)) && break
    done

    COMMON_TEMP_FILE_GENERATED_BITS="$RESULT"

    return $ALL_OK
}

#
# Функции для генерации входного файла
#

# @brief    Функция кодирования временного файла во входной файл
# @details  Данная функция выполняет кодирование данных временного файла, 
#               содержащего последовательность бит, в COMMON_INPUT_FILE_PATH файл логического анализатора
# @note     Используемые переменные:
#               COMMON_TEMP_FILE_PATH
#               COMMON_INPUT_FILE_PATH
#               COMMON_INPUT_FILE_GARBAGE_BEFORE
#               COMMON_INPUT_FILE_GARBAGE_AFTER
#               COMMON_INPUT_FILE_DATA_LENGTH
#               COMMON_INPUT_FILE_SYNC_LENGTH
#               COMMON_INPUT_FILE_LEVEL_CORRUPT_CHANCE
# @return   Возвращает ALL_OK в случае успешного выполнения операции.
#               В противном случае, возвращает NOT_OK
function inputFileEncodeTempFile()
{
    local TEMP_FILE_PATH="${COMMON_TEMP_FILE_PATH}.${TEMP_FILE_SUFFIX_FOR_INPUT}"
    local INPUT_FILE_PATH="$2"

    truncate -s 0 "$COMMON_INPUT_FILE_PATH" || return $NOT_OK
    exec       3>>"$COMMON_INPUT_FILE_PATH"

    local SYNC_LENGTH_LEFT=$((COMMON_INPUT_FILE_SYNC_LENGTH / 2))
    local SYNC_LENGTH_RIGHT=$((COMMON_INPUT_FILE_SYNC_LENGTH - SYNC_LENGTH_LEFT))

    if ((COMMON_INPUT_FILE_SYNC_LENGTH == 1))
    then
        SYNC_LENGTH_LEFT=1
        SYNC_LENGTH_RIGHT=0
    fi

    inputFileEncodeLevel "$INPUT_FILE_LEVEL_SYNC" "$SYNC_LENGTH_LEFT" 0
    local BYTES_SYNC_LEFT="$INPUT_FILE_ENCODED_LEVEL_BYTES"

    inputFileEncodeLevel "$INPUT_FILE_LEVEL_SYNC" "$SYNC_LENGTH_RIGHT" 0
    local BYTES_SYNC_RIGHT="$INPUT_FILE_ENCODED_LEVEL_BYTES"

    inputFileEncodeLevel "$INPUT_FILE_LEVEL_DATA_0" "$COMMON_INPUT_FILE_DATA_LENGTH" 0
    local BYTES_DATA_0="$INPUT_FILE_ENCODED_LEVEL_BYTES"

    inputFileEncodeLevel "$INPUT_FILE_LEVEL_DATA_1" "$COMMON_INPUT_FILE_DATA_LENGTH" 0
    local BYTES_DATA_1="$INPUT_FILE_ENCODED_LEVEL_BYTES"

    inputFileEncodeLevel "$INPUT_FILE_LEVEL_DATA_0" "$COMMON_INPUT_FILE_DATA_LENGTH" 100
    local BYTES_DATA_0_CORRUPTED="$INPUT_FILE_ENCODED_LEVEL_BYTES"

    inputFileEncodeLevel "$INPUT_FILE_LEVEL_DATA_1" "$COMMON_INPUT_FILE_DATA_LENGTH" 100
    local BYTES_DATA_1_CORRUPTED="$INPUT_FILE_ENCODED_LEVEL_BYTES"

    if ((COMMON_INPUT_FILE_GARBAGE_BEFORE > 0))
    then
        inputFileEncodeLevel "$((RANDOM % 2))" "$COMMON_INPUT_FILE_GARBAGE_BEFORE" 0
        printf "%s" "$INPUT_FILE_ENCODED_LEVEL_BYTES" >&3
    fi

    ((SYNC_LENGTH_RIGHT > 0)) && printf '%s' "$BYTES_SYNC_RIGHT" >&3

    awk -v syncLeft="$BYTES_SYNC_LEFT" \
        -v syncRight="$BYTES_SYNC_RIGHT" \
        -v data0="$BYTES_DATA_0" \
        -v data1="$BYTES_DATA_1" \
        -v data0Currupted="$BYTES_DATA_0_CORRUPTED" \
        -v data1Currupted="$BYTES_DATA_1_CORRUPTED" \
        -v curruptChance="$COMMON_INPUT_FILE_LEVEL_CORRUPT_CHANCE" \
    '
    function write(text)
    {
        printf "%s", text
    }

    BEGIN {
        srand()
    }

    {
        for (i = 1; i <= length($0); ++i) 
        {
            bit = substr($0, i, 1)

            if (bit != "0" && bit != "1")
            {
                continue
            }

            if (syncLeft != "")
            {
                write(syncLeft)
            }

            if (rand() * 100 < curruptChance) 
            {
                if (bit == "0")
                {
                    write(data0Currupted)
                }
                else if (bit == "1")
                {
                    write(data1Currupted)
                }
            }
            else 
            {
                if (bit == "0")
                {
                    write(data0)
                }
                else if (bit == "1")
                {
                    write(data1)
                }
            }

            if (syncRight != "")
            {
                write(syncRight)
            }
        }
    }
    ' "$TEMP_FILE_PATH" >&3

    ((SYNC_LENGTH_LEFT > 0)) && printf '%s' "$BYTES_SYNC_LEFT" >&3

    if ((COMMON_INPUT_FILE_GARBAGE_AFTER > 0))
    then
        inputFileEncodeLevel "$((RANDOM % 2))" "$COMMON_INPUT_FILE_GARBAGE_AFTER" 0
        printf "%s" "$INPUT_FILE_ENCODED_LEVEL_BYTES" >&3
    fi

    exec 3>&-

    return $ALL_OK
}

# @brief    Сгенерированная функцией inputFileEncodeLevel() последовательность байт
INPUT_FILE_ENCODED_LEVEL_BYTES=""

# @brief    Флаг поврежденности логического уровня в сгенерированной функцией inputFileEncodeLevel() последовательности байт
INPUT_FILE_ENCODED_LEVEL_IS_CORRUPTED=0

# @brief    Функция кодирования логического уровня
# @details  Данная функция выполняет кодирование логического уровня LEVEL в 
#               последовательность из REPEAT_COUNT одинаковых байт, записывая их в INPUT_FILE_ENCODED_LEVEL_BYTES.
#           Если случайное значение [0:100] меньше CORRUPT_CHANCE и LEVEL не равен INPUT_FILE_LEVEL_SYNC,
#               три центральных байта будут заменены на байты противоположного логического уровня.
#           Флаг повреждения логического уровня записывается в INPUT_FILE_ENCODED_LEVEL_IS_CORRUPTED
# @param    LEVEL           Логический уровень. Допустимые значения: INPUT_FILE_LEVEL_DATA_0, INPUT_FILE_LEVEL_DATA_1, INPUT_FILE_LEVEL_SYNC
# @param    REPEAT_COUNT    Количество повторений уровня. Должно быть не меньше 1
# @param    CORRUPT_CHANCE  Шанс повреждения уровня. Должен быть в диапазоне [0:100]
# @return   Всегда возвращает ALL_OK
function inputFileEncodeLevel()
{
    local LEVEL="$1"
    local REPEAT_COUNT="$2"
    local CORRUPT_CHANCE"$3"

    local RESULT=""

    INPUT_FILE_ENCODED_LEVEL_BYTES=""
    INPUT_FILE_ENCODED_LEVEL_IS_CORRUPTED=0

    if ((LEVEL == INPUT_FILE_LEVEL_SYNC))
    then
        CORRUPT_CHANCE=0
    fi

    inputFileLevelToByte "$LEVEL"
    local BYTE="$INPUT_FILE_ENCODED_BYTE"

    local INVERTED_BYTE="$BYTE"
    local IS_CORRUPTED=0
    if (($(randomChance) < CORRUPT_CHANCE)) &&
       ((REPEAT_COUNT >= 3))
    then
        IS_CORRUPTED=1

        if [[ "$BYTE" == "$INPUT_FILE_ENCODED_DATA_1" ]]
        then
            INVERTED_BYTE="$INPUT_FILE_ENCODED_DATA_0"
        fi

        if [[ "$BYTE" == "$INPUT_FILE_ENCODED_DATA_0" ]]
        then
            INVERTED_BYTE="$INPUT_FILE_ENCODED_DATA_1"
        fi
    fi

    local CORRUPT_START=$((REPEAT_COUNT / 2 - 1))

    local i=0
    for ((i = 0; i < REPEAT_COUNT; ++i))
    do
        RESULT+="$BYTE"
    done

    if ((IS_CORRUPTED))
    then
        RESULT="${RESULT:0:CORRUPT_START}${INVERTED_BYTE}${INVERTED_BYTE}${INVERTED_BYTE}${RESULT:CORRUPT_START+3}"
    fi

    INPUT_FILE_ENCODED_LEVEL_BYTES="$RESULT"
    INPUT_FILE_ENCODED_LEVEL_IS_CORRUPTED=$IS_CORRUPTED

    return $ALL_OK
}

# @brief    Преобразованный функцией inputFileLevelToByte() логический уровень
INPUT_FILE_ENCODED_BYTE=""

# @brief    Функция преобразования логического уровня в байт входного файла
# @details  Данная функция выполняет преобразование логического уровня в байт входного файла и
#               записывает его в INPUT_FILE_ENCODED_BYTE
# @param    LEVEL Логический уровень
# @return   Возвращает ALL_OK в случае успешного выполнения операции.
#               В противном случае, возвращает NOT_OK
function inputFileLevelToByte()
{
    local LEVEL=$1

    case "$LEVEL" in
        $INPUT_FILE_LEVEL_DATA_0)
            INPUT_FILE_ENCODED_BYTE="$INPUT_FILE_ENCODED_DATA_0"
        ;;
        $INPUT_FILE_LEVEL_DATA_1)
            INPUT_FILE_ENCODED_BYTE="$INPUT_FILE_ENCODED_DATA_1"
        ;;
        $INPUT_FILE_LEVEL_SYNC)
            INPUT_FILE_ENCODED_BYTE="$INPUT_FILE_ENCODED_SYNC"
        ;;
        *)
            INPUT_FILE_ENCODED_BYTE=""
            return $NOT_OK
        ;;
    esac

    return $ALL_OK
}

#
# Функции для генерации выходного файла
#

# @brief    Функция кодирования временного файла в выходной файл
# @details  Данная функция выполняет преобразование временного файла, содержащего
#               последовательность бит, в бинарный выходной файл.
#           Каждые восемь бит объединяются в один байт и пишутся в COMMON_OUTPUT_FILE_PATH.
#           Первый считанный бит становится старшим битом выходного байта.
#           Если количество бит не кратно восьми, недостающие младшие биты
#               последнего байта заполняются нулями.
# @note     Используемые переменные:
#               COMMON_TEMP_FILE_PATH
#               COMMON_OUTPUT_FILE_PATH
# @return   Возвращает ALL_OK в случае успешного выполнения операции.
#               В противном случае, возвращает NOT_OK
function outputFileEncodeTempFile()
{
    local TEMP_FILE_PATH="${COMMON_TEMP_FILE_PATH}.${TEMP_FILE_SUFFIX_FOR_OUTPUT}"

    truncate -s 0 "$COMMON_OUTPUT_FILE_PATH" || return $NOT_OK
    exec       3>>"$COMMON_OUTPUT_FILE_PATH"

    awk \
    '
    function write(value)
    {
        printf "%c", value
    }

    function shiftLeft(value, count)
    {
        while (count > 0)
        {
            value *= 2
            --count
        }
        return value
    }

    function processLine(line, i, bit)
    {
        for (i = 1; i <= length(line); ++i)
        {
            bit = substr(line, i, 1)

            if (bit != "0" && bit != "1")
                continue

            byte = shiftLeft(byte, 1) + bit
            ++bitCount

            if (bitCount == 8)
            {
                write(byte)
                byte     = 0
                bitCount = 0
            }
        }

        if (bitCount > 0)
        {
            byte = shiftLeft(byte, 8 - bitCount)
            write(byte)
            byte     = 0
            bitCount = 0
        }
    }

    BEGIN {
        byte      = 0
        bitCount  = 0
        isNotEOF  = 0
        lastLine  = 0
    }

    {
        if (isNotEOF)
        {
            processLine(lastLine)
        }

        lastLine = $0
        isNotEOF = 1
    }

    ' "$TEMP_FILE_PATH" >&3

    exec 3>&-

    return $ALL_OK
}

#
# Точка входа в скрипт
#

trap cleanup EXIT
main "$@"
exit $?
